<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/1_10_b%E1%BB%95_sung_to%C3%A1n_h%E1%BB%8Dc_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

In [2]:
#Tao ma tran X (5, 3)
X = np.array([[1, 2, 3, 4, 5],
              [6, 7, 8, 9, 2],
              [4, 5, 7, 2, 1]])
X = np.reshape(X, (5, 3))
print('dimension: ', X.ndim)
print('X shape: ', X.shape)
print(X)

dimension:  2
X shape:  (5, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 4 5]
 [7 2 1]]


In [3]:
#Tạo vector trọng số w (3, 1)
w = np.reshape([2, 4, 2], (3, 1))
print('dimension: ', w.ndim)
print('w shape: ', w.shape)
print(w)

dimension:  2
w shape:  (3, 1)
[[2]
 [4]
 [2]]


In [4]:
#Tao vector y (5, 1)
y= np.reshape([1,2, 3, 2, 1], (5, 1))

#Hãy tính gia thuyet h = X.w
h = np.dot(X, w)
print('dimension: ', h.ndim)
print(h.shape)
print(h)

dimension:  2
(5, 1)
[[16]
 [40]
 [64]
 [30]
 [24]]


In [5]:
#Hãy tính hiệu h - y
hieu = h - y
print('dimension: ', hieu.ndim)
print(hieu.shape)
print(hieu)

dimension:  2
(5, 1)
[[15]
 [38]
 [61]
 [28]
 [23]]


In [7]:
#hãy tính (h-y).X --> (5x1).(5x3) --> (3x5).(5x1) = XT.(h- y)
h2 = np.dot(X.T, hieu)
print('dimension: ', h2.ndim)
print(h2.shape)
print(h2)

dimension:  2
(3, 1)
[[811]
 [866]
 [985]]
