<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [ ]:
#Code 
np.arange(-15, 27, 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [ ]:
#Code
np.random.normal(2.7, 1.2, 40)

array([2.80674756, 5.20824029, 2.81707641, 2.37324531, 3.67519775,
       3.40700669, 3.81063998, 3.71088444, 1.99704905, 1.07859064,
       4.30167186, 1.54722607, 3.75643666, 3.9083011 , 2.71106366,
       3.73603144, 4.46279542, 6.01756701, 1.17821085, 2.97238565,
       0.52611876, 2.8128201 , 3.24835074, 2.69586935, 1.94944335,
       1.37599372, 2.54580953, 3.87849577, 4.15511978, 4.50846119,
       1.29469237, 3.66282205, 2.54247229, 2.114257  , 3.64135635,
       2.3556566 , 2.86006426, 3.38314825, 4.75411629, 5.25410074])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [ ]:
#Code
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], size = 17)

array(['Viet Nam', 'Viet Nam', 'Russia', 'Singapore', 'Britain', 'Russia',
       'Singapore', 'France', 'Britain', 'Britain', 'Britain', 'France',
       'Singapore', 'Britain', 'Russia', 'Russia', 'Russia'], dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [ ]:
#Code
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17, p= [0.6, 0.1, 0.1, 0.1, 0.1])

array(['Viet Nam', 'Viet Nam', 'France', 'Viet Nam', 'Viet Nam', 'Russia',
       'Viet Nam', 'France', 'Viet Nam', 'Russia', 'Viet Nam', 'France',
       'Viet Nam', 'Britain', 'Viet Nam', 'Viet Nam', 'Viet Nam'],
      dtype='<U9')

In [ ]:
import scipy.stats as st

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [ ]:
#Code
st.norm.rvs(12.7, 2.6, 30)

array([13.0879663 , 10.38928409, 14.76239185, 13.50608795,  6.24411657,
       16.46695184, 10.31756313, 14.43325269, 12.41627759, 13.15124597,
       16.92506516,  9.2038644 , 15.12285531, 17.48718393, 12.01037653,
       10.33511985, 12.55824029, 11.91466438, 16.74627938, 13.02773258,
       11.67312898, 14.27773498, 14.97200348, 11.36398972, 14.73106044,
        9.64666362, 16.53102569, 14.23275837,  8.29442741,  9.20216316])