<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/bai_tap_sinh_mau_ngau_nhien.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Sử dụng thư viện Numpy

1. Sinh mẫu ngẫu nhiên bằng hàm arange trong khoảng [-15, 27] với khoảng cách là 0.7 và in kết quả ra màn hình

In [2]:
np.arange(-15, 27, 0.7)

array([-15. , -14.3, -13.6, -12.9, -12.2, -11.5, -10.8, -10.1,  -9.4,
        -8.7,  -8. ,  -7.3,  -6.6,  -5.9,  -5.2,  -4.5,  -3.8,  -3.1,
        -2.4,  -1.7,  -1. ,  -0.3,   0.4,   1.1,   1.8,   2.5,   3.2,
         3.9,   4.6,   5.3,   6. ,   6.7,   7.4,   8.1,   8.8,   9.5,
        10.2,  10.9,  11.6,  12.3,  13. ,  13.7,  14.4,  15.1,  15.8,
        16.5,  17.2,  17.9,  18.6,  19.3,  20. ,  20.7,  21.4,  22.1,
        22.8,  23.5,  24.2,  24.9,  25.6,  26.3,  27. ])

2. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 2.7 std = 1.2 và size = 40
In kết quả ra màn hình

In [3]:
np.random.normal(2.7, 1.2, 40)

array([4.46139814, 2.10018508, 2.78132534, 2.36224895, 3.93802642,
       3.74366024, 1.2112945 , 1.11968189, 3.20414478, 4.12438066,
       1.92149953, 3.75551822, 2.63257298, 2.94612963, 0.86532074,
       5.03430308, 3.79781645, 3.79281814, 0.84866939, 0.96226628,
       3.77633426, 1.06586511, 2.84903083, 2.65730191, 2.39183553,
       2.57580349, 1.53403341, 2.40767654, 4.07336637, 1.54435853,
       1.48201176, 2.05558675, 2.58520581, 1.77689916, 2.06432417,
       2.88696414, 3.57136643, 3.00435337, 1.88730379, 3.14667717])

3. Sinh mẫu ngẫu nhiên từ vector ['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'] 

với kích thước là 17 theo phân phối chuẩn

In [4]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], size = 17)

array(['Singapore', 'Russia', 'Russia', 'Singapore', 'Singapore',
       'France', 'Russia', 'Viet Nam', 'France', 'Viet Nam', 'Russia',
       'Britain', 'Viet Nam', 'Britain', 'France', 'France', 'Russia'],
      dtype='<U9')

4. Sinh mẫu ngẫu nhiên ở câu 3 nhưng không theo phân phối chuẩn mà theo 1 vector đặc tả giá trị xác suất do bạn chọn

In [5]:
np.random.choice(['Viet Nam', 'Britain', 'France', 'Russia', 'Singapore'], 17, p= [0.6, 0.1, 0.1, 0.1, 0.1])

array(['Viet Nam', 'Singapore', 'Viet Nam', 'Russia', 'Viet Nam',
       'Viet Nam', 'France', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Russia',
       'Britain', 'Viet Nam', 'Viet Nam', 'Viet Nam', 'Britain',
       'Viet Nam'], dtype='<U9')

In [6]:
import scipy.stats as st

Sử dụng thư việc scipy.stats để sinh mẫu ngẫu nhiên

1. Sinh mẫu ngẫu nhiên theo phân phối chuẩn với mean = 12.7, std = 2.6 và size = 30. In kết quả ra màn hình

In [7]:
st.norm.rvs(12.7, 2.6, 30)

array([14.14041995,  9.83413368, 11.13907353,  8.40517536, 12.32777316,
        9.37574535, 10.23792442, 15.80424874, 18.33620105, 11.40658865,
       13.75364259, 15.0958273 , 13.48800076, 11.34858083,  8.51573384,
       13.50236693, 11.98739274, 14.33942754, 18.33029004, 11.71548272,
       12.68899268, 13.639089  , 12.21024144, 14.02184721, 16.08762541,
       12.56067874, 11.02605253, 12.43370212,  9.07016764, 15.17299424])