<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/numpy03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Câu 1: Hãy trình bày cú pháp của hàm apply_along_axis() và ý nghĩa của từng tham số của hàm
này.

numpy.apply_along_axis(func1d, axis, arr, *args, **kwargs)
+ Giup chúng ta áp dụng các hàm cần thiết cho các lát cắt 1D của mảng đã cho

func1dfunction (M,) -> (Nj…) 
+ Hàm này dùng cho mảng 1D. Nó được áp dụng cho các lát arr 1D dọc theo trục được chỉ định.

axis: integer
+ Trục dọc theo arr được cắt.

arr: ndarray (Ni…, M, Nk…)

+ Nhập mảng.

args: any
+ Đối số bổ sung cho func1d.

kwargs: any
+ Các đối số được đặt tên bổ sung cho func1d

Câu 2: Tạo một ma trận A15x17 có giá trị ngẫu nhiên

In [1]:
import numpy as np
import random 

In [4]:
A = np.array([random.randint(0,10) for i in range(255)])
A = A.reshape((15,17))
print(A)

[[10  4  5  2  5  1  8  4  3  5  7  6  6  9  0  7  6]
 [ 6  3  4  7  0  7  8  4  8  4  6  5  4  8  1  1  6]
 [ 5  5  0  3  3  8  7  1  7  8  2  6  5  7  5  9  6]
 [10  6  9  4 10  9  8  3  8  0  8  1  8  3  2  3  1]
 [ 8  5  8  8  6  7  8  1  8  3  7  6  3  4  6  0  1]
 [ 6  8 10  8  0  7  8  9 10  1  0  3  1  3  3 10  0]
 [ 1  5  6  9  5  7 10  3 10  7  2  1  4  1  8  9  8]
 [ 7  8  7  8 10  6  3 10  3  5  7  8  9  4  0 10  9]
 [ 2 10  9  1  3  8  3  9  2  9  2  8  4  0 10  1 10]
 [ 3  8  5 10  6  9  0  4  0  4  9  6  5  2  2  7  4]
 [ 0  7  0  7  9  6  6  5  1  8  9  0  8 10  9  5  7]
 [ 5  0  4 10  2  8 10 10  0  9  8  9  8  3  4  3  5]
 [ 8  1  0  2  9  6  6  7  0  2  2  7  0  6 10  1  3]
 [ 7  8  6  1  4  4  7  6  5  9  5  4  9  2  6  6  8]
 [ 6  3  9  2  4  7  8  8  5  1  4  1  8  2 10  1  0]]


Câu 3: Xây dựng hàm tìm giá trị lớn nhất có tên là tim_gia_tri_lon_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử lớn nhất của vector này. Áp dụng hàm này
theo từng hàng của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [5]:
def max(A):
  max = 0
  for i in range(len(A)):
    if max < A[i]:
      max = A[i]
    else:
      max = max
  return max

print(np.apply_along_axis(max, 1, A))

[10  8  9 10  8 10 10 10 10 10 10 10 10  9 10]


Câu 4: Xây dựng hàm tìm giá trị nhỏ nhất có tên là tim_gia_tri_nho_nhat(vector_a) có tham số
đầu vào là 1 vector a và giá trị trả về là giá trị phần tử nhỏ nhất của vector này. Áp dụng hàm này
theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [6]:
def min(A):
  min = 10
  for i in range(len(A)):
    if min > A[i]:
      min = A[i]
    else:
      min = min
  return min

print(np.apply_along_axis(min, 1, A))

[0 0 0 0 0 0 1 0 0 0 0 0 0 1 0]


Câu 5: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong(vector_a) có tham số đầu vào là 1
vector a và giá trị trả về là tổng các phần tử của vector này. Áp dụng hàm này theo từng hàng của
ma trận A ở Câu 1 và xuất kết quả ra màn hình.

In [7]:
def sum(A):
  sum = 0
  for i in range(len(A)):
    sum += A[i]
  return sum 

print(np.apply_along_axis(sum,1,A))

[ 88  82  87  93  89  87  96 114  91  84  97  98  70  97  79]


Câu 6: Xây dựng hàm tìm giá trị lớn nhất có tên là tinh_tong_2(vector_a) có tham số đầu vào là
1 vector a và giá trị trả về là tổng các phần tử có chỉ số lẻ (1 – 3 – 5 , .v.v.) của vector này. Áp
dụng hàm này theo từng cột của ma trận A ở Câu 1 và xuất kết quả ra màn hình. Tiếp tục áp dụng
hàm này theo từng hàng của ma trận A kể trên và xuất kết quả ra màn hình.

In [12]:
def sum2(A):
  sum = 0
  for i in range(len(A)):
    if i %2 !=0:
      sum += A[i]
  return sum

print(np.apply_along_axis(sum2,1,A))

[38 39 47 29 34 49 42 59 46 50 48 52 32 40 25]
