<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 

Baì 1: Trong Toán học, ma trận (matrix) là một mảng 2 chiều chứa số hoặc các đối
tượng toán học khác. Một cách tổng quát ma trận A có m hàng và n cột chứa các số thực, ký hiệu
là A ∈ $R^m×^n$ hay Am×n hay A = (ai,j)m×n


Sử dụng thư viện NumPy, hãy tạo ra một ma trận A ∈ $R^7×^5$, giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.


In [ ]:
A = np.random.randint(0,10,(7,5))
print(A)

[[9 1 6 6 8]
 [7 7 8 6 0]
 [4 1 0 0 7]
 [8 9 3 7 3]
 [8 9 5 9 1]
 [1 8 5 1 5]
 [0 4 5 6 8]]


Bài 2 – Ma trận không (zero matrix): Ma trận Am×n được gọi là ma trận không khi ai,j = 0, ∀i,j.
Sử dụng thư viện NumPy, hãy tạo một ma trận 0 - A6×7. Gợi ý: sử dụng hàm numpy.zeros((m,n)).
Kết quả xuất ra màn hình.

In [ ]:
A = np.zeros((6,7))
print(A)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


Bài 3 – Ma trận vuông: Là ma trận có số hàng và số cột bằng nhau. Sử dụng thư viện NumPy,
hãy tạo ra một ma trận A ∈ $R^7×^7$ , giá trị các phần tử của ma trận được sinh ngẫu nhiên. Kết quả xuất ra màn hình.

In [ ]:
A = np.random.randn(7,7)
print(A)

[[ 0.03048632 -0.64923219 -0.81191171 -1.20304962  1.65543351 -0.50449556
  -0.78976631]
 [ 0.19936375 -1.15043244 -0.34210594  0.34630305 -0.73752957  0.85592165
   0.00252605]
 [-1.50989238  0.47778961  0.65302719  0.97578465 -0.10134803  0.08826062
  -0.54371375]
 [ 0.62080542 -0.13549054 -0.685972   -1.32780513  0.61807188 -1.77764501
   0.89742543]
 [-1.36952604 -1.10390944 -1.15391233  0.76824067 -0.48679593  0.71345843
  -0.38036602]
 [ 0.57039785 -0.08445098 -0.47380036 -0.34181564  0.58193985  1.64790324
  -0.32777706]
 [ 0.38240157 -1.38684188 -0.11823852  1.14851975  0.04834173 -1.91317436
   0.60107633]]


Bài 4 – Ma trận chéo (diagonal matrix): Ma trận vuông có các phần tử trên đường chéo ai,i ≠ 0
trong khi các phần tử còn lại ai,j = 0, ∀i ≠ j.
Sử dụng thư viện NumPy, hãy tạo một ma trận chéo A6×6 với phần tử nằm trên đường chéo có giá
trị là 15. Gợi ý: sử dụng kết hợp hàm numpy.zeros() và numpy.fill_diagonal(). Kết quả xuất ra
màn hình.

In [ ]:
A = np.zeros([6,6], dtype = int)
np.fill_diagonal(A, 15)
print(A)

[[15  0  0  0  0  0]
 [ 0 15  0  0  0  0]
 [ 0  0 15  0  0  0]
 [ 0  0  0 15  0  0]
 [ 0  0  0  0 15  0]
 [ 0  0  0  0  0 15]]


Bài 5 – Ma trận tam giác trên (upper triangular matrix): Ma trận vuông An×n được gọi là ma
trận tam giác trên nếu các phần tử nằm trên đường chéo đều khác 0 và các phần tử nằm dưới đường
chéo đều bằng 0.
Sử dụng thư viện NumPy, hãy tạo một ma trận tam giác trên A8×8. Gợi ý: sử dụng hàm
numpy.triu(). Kết quả xuất ra màn hình.

In [ ]:
A = np.triu(np.random.randint(1,10,[8,8]), k = 0)
print(A)

[[9 4 8 8 7 3 8 7]
 [0 9 4 6 4 2 1 6]
 [0 0 1 9 9 7 8 4]
 [0 0 0 8 5 8 9 2]
 [0 0 0 0 4 6 3 9]
 [0 0 0 0 0 9 8 9]
 [0 0 0 0 0 0 9 6]
 [0 0 0 0 0 0 0 1]]


Bài 6 – Ma trận tam giác dưới (lower triangular matrix): Tương tự bài 5, bạn hãy xây dựng
ma trận tam giác dưới. Kết quả xuất ra màn hình.

In [ ]:
A = np.tril(np.random.randint(1,10,[8,8]), k = 0)
print(A)

[[2 0 0 0 0 0 0 0]
 [8 7 0 0 0 0 0 0]
 [4 8 7 0 0 0 0 0]
 [1 1 1 2 0 0 0 0]
 [5 2 5 3 8 0 0 0]
 [8 1 6 1 1 9 0 0]
 [4 7 6 4 2 5 9 0]
 [7 7 5 8 1 3 9 8]]


Bài 7 – Ma trận đơn vị (identity matrix): Ma trận đơn vị In có số chiều n là một ma trận vuông
mà mọi phần tử trên đường chéo chính bằng 1. Sử dụng thư viện NumPy, hãy tạo ra một ma trận
I9
. Kết quả xuất ra màn hình. Gợi ý: sử dụng hàm numpy.identity()

In [ ]:
A = np.identity(9, dtype = int)
print(A)

[[1 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1]]


Bài 8 – Phép toán trên ma trận: sử dụng thư viện NumPy để thực hiện các yêu cầu sau:

 Phép cộng ma trận: Am×n + Bm×n = Cm×n. Hãy sinh ngẫu nhiên 2 ma trận có kích thước 6x7. Thực hiện phép cộng 2 ma trận trên. Xuất giá trị các ma trận ra màn hình.

 Phép nhân vô hướng một số với ma trận: Hãy sinh ngẫu nhiên 1 ma trận có kích thước 5x8. Thực hiện nhân vô hướng 1 số được nhập từ bàn phím với ma trận này. Kết quả xuất ra màn hình.

 Phép chuyển vị ma trận: Sinh ngẫu nhiên một ma trận có kích thước 3x7. Thực hiện phép chuyển vị đối với ma trận này. Xuất các ma trận này ra màn hình.

 Phép nhân 2 ma trận: Am×n ∙ Bn×p = Cm×p. Hãy sinh ngẫu nhiên 2 ma trận A5×7 và B7×3, tiến hành nhân 2 ma trận này để thu được ma trận C5×3. Xuất các ma trận trên ra màn hình.
Gợi ý: sử dụng hàm numpy.dot()

 Ma trận khả nghịch: ma trận vuông An×n gọi là khả nghịch (hay không suy biến) nếu tồn tại một ma trận vuông Bn×n sao cho A ∙ B = In . Khi này, B được gọi là ma trận nghịch đảo của A và ký hiệu là $A^−1$
. Cho ma trận A5×7, hãy tính ma trận khả nghịch của A. Gợi

ý: sử dụng hàm numpy.linalg.inv()

In [ ]:
A = np.random.randint(0,10,[6,7])
print("Ma trận ngẫu nhiên A: \n", A)
B = np.random.randint(0,10,[6,7])
print("Ma trận ngẫu nhiên B: \n", B)
C = A+B
print("Cộng hai ma trận A và B: \n", C)

Ma trận ngẫu nhiên A: 
 [[6 8 0 2 3 7 1]
 [5 2 2 8 2 9 2]
 [9 8 9 0 6 1 2]
 [2 9 9 4 0 5 4]
 [5 0 1 6 5 8 7]
 [9 5 1 0 3 7 6]]
Ma trận ngẫu nhiên B: 
 [[3 7 7 4 0 6 9]
 [0 6 6 0 9 4 5]
 [0 4 3 3 9 3 3]
 [5 3 7 7 5 6 1]
 [1 3 6 8 4 3 2]
 [0 7 3 8 5 5 9]]
Cộng hai ma trận A và B: 
 [[ 9 15  7  6  3 13 10]
 [ 5  8  8  8 11 13  7]
 [ 9 12 12  3 15  4  5]
 [ 7 12 16 11  5 11  5]
 [ 6  3  7 14  9 11  9]
 [ 9 12  4  8  8 12 15]]


In [ ]:
n = int(input("nhập số: "))
A = np.random.randint(0,10, [5,8])
print("sinh ngẫu nhiên ma trận: \n", A)
print("Phép nhân vô hướng với 1 số: \n", A*n)


nhập số: 4
sinh ngẫu nhiên ma trận: 
 [[8 5 9 9 4 8 1 1]
 [7 9 0 0 1 7 0 9]
 [1 4 4 4 3 7 9 7]
 [0 0 0 5 5 9 2 4]
 [5 3 4 7 0 8 3 7]]
Phép nhân vô hướng với 1 số: 
 [[32 20 36 36 16 32  4  4]
 [28 36  0  0  4 28  0 36]
 [ 4 16 16 16 12 28 36 28]
 [ 0  0  0 20 20 36  8 16]
 [20 12 16 28  0 32 12 28]]


In [ ]:
A = np.random.randint(0,10,[3,7])
print("sinh ngẫu nhiên ma trận: \n", A)
print("Chuyển vị ma trận: \n", A.T)

sinh ngẫu nhiên ma trận: 
 [[9 4 9 8 6 9 4]
 [9 4 7 6 9 8 8]
 [2 3 9 2 5 7 5]]
Chuyển vị ma trận: 
 [[9 9 2]
 [4 4 3]
 [9 7 9]
 [8 6 2]
 [6 9 5]
 [9 8 7]
 [4 8 5]]


In [ ]:
A = np.random.randint(0,10,[5,7])
print("Ma trận A: \n", A)
B =  np.random.randint(0,10,[7,3])
print("Ma trận B: \n", B)
C = np.dot(A,B)
print("Nhân hai ma trận : \n", C)


Ma trận A: 
 [[4 7 0 4 9 5 6]
 [2 6 0 2 4 7 2]
 [7 0 9 3 5 7 2]
 [0 1 1 9 9 5 3]
 [6 7 9 7 4 6 0]]
Ma trận B: 
 [[1 6 7]
 [5 2 4]
 [0 8 7]
 [7 1 1]
 [7 2 8]
 [4 4 5]
 [5 9 8]]
Nhân hai ma trận : 
 [[180 134 205]
 [112  80 123]
 [101 173 206]
 [166  84 141]
 [142 161 202]]


In [ ]:
A = np.random.randint(0,10,[7,7])
print("Ma trận A: \n", A)
I = np.linalg.inv(A)
print(" Ma trận khả nghịch của A: \n", I)


Ma trận A: 
 [[6 3 8 3 3 6 4]
 [2 9 8 9 0 2 1]
 [1 8 0 6 9 2 9]
 [0 5 9 6 0 4 8]
 [4 3 7 4 6 8 7]
 [8 1 9 4 7 3 1]
 [1 0 2 0 1 5 0]]
 Ma trận khả nghịch của A: 
 [[ 0.147343    0.17149758 -0.21980676 -0.39130435  0.65458937 -0.23429952
  -0.75120773]
 [ 0.35771512 -0.18451954  0.36799876  0.32479552 -1.04406419  0.15175539
   0.81696322]
 [ 0.09574544 -0.22876309  0.23421581  0.44317693 -0.8723992   0.29921797
   0.74469077]
 [-0.46841967  0.44115607 -0.49793131 -0.59255273  1.56831444 -0.32387478
  -1.25612235]
 [-0.05770794 -0.16585354  0.23362988  0.24106759 -0.55648826  0.26089348
   0.58313005]
 [-0.05622519  0.09037643 -0.09645095 -0.14722342  0.32933946 -0.12500598
  -0.06426077]
 [ 0.04814177 -0.00337208 -0.07181805 -0.05854498  0.29308366 -0.12605826
  -0.37415698]]


Bài 9 – Vector là dạng ma trận đặc biệt: Sử dụng numpy để thực hiện các yêu cầu sau

 Vector hàng (row vector) thực chất là ma trận có kích thước 1 × n. Hãy tạo ngẫu nhiên 1 vector hàng - x có kích thước 1 × 8. Kết quả xuất ra màn hình.

 Vector cột (column vector) thực chất là ma trận có kích thước m × 1. Hãy tạo ngẫu nhiên 1 vector cột – x có kích thước 8 × 1. Kết quả xuất ra màn hình.

In [ ]:
rvector = np.random.randint(0,10,[1,8])
print(" Vector hàng: \n", rvector)
cvector = np.random.randint(0,10,[8,1])
print("Vector cột: \n", cvector)

 Vector hàng: 
 [[8 3 8 8 0 4 6 4]]
Vector cột: 
 [[2]
 [6]
 [9]
 [7]
 [2]
 [1]
 [9]
 [0]]
