<a href="https://colab.research.google.com/github/lmquann/leminhquan/blob/main/numpy04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np 

Câu 1: Sử dụng thư viện Numpy, hãy tạo một vector a có 7 chiều (tương ứng 7 phần tử) với giá
trị các phần tử được sinh bằng hàm (kết quả xuất ra màn hình):
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Ghi chú: sau mỗi lần sinh ra giá trị cho vector, hãy cho biết số chiều của vector được sinh ra và
số chiều của vector chuyển vị của vector đó; cho biết kích thước của vector a và vector chuyển vị
của vector a.
Gợi ý: tham khảo ndim và shape.

In [27]:
#Tạo vector bằng hàm arrange: 
A = np.arange(0,7)
#Chuyển vị vector :
A1 = np.transpose(A)
print(A)
print(A.ndim, A1.ndim)
print(A.shape,A1.shape)
#Tạo vector bằng hàm linspace:
B = np.linspace(1,8, 7)
#Chuyển vị vector :
B1 = np.transpose(B)
print(B)
print(B.ndim, B1.ndim)
print(B.shape,B1.shape)
#Tạo vector bằng hàm logspace:
C = np.logspace(1, 8, 7)
#Chuyển vị vector:
C1 = np.transpose(C)
print(C)
print(C.ndim, C1.ndim)
print(C.shape,C1.shape)
#TTạo vector bằng hàm random.ranđ:
D = np.random.rand(1,7)
#Chuyển vị vector:
D1 = np.transpose(D)
print(D)
print(D.ndim, D1.ndim)
print(D.shape,D1.shape)

[0 1 2 3 4 5 6]
1 1
(7,) (7,)
[1.         2.16666667 3.33333333 4.5        5.66666667 6.83333333
 8.        ]
1 1
(7,) (7,)
[1.00000000e+01 1.46779927e+02 2.15443469e+03 3.16227766e+04
 4.64158883e+05 6.81292069e+06 1.00000000e+08]
1 1
(7,) (7,)
[[0.26912365 0.6082986  0.92621137 0.56196087 0.6658238  0.0184974
  0.5059676 ]]
2 2
(1, 7) (7, 1)


Câu 2: Sử dụng thư viện Numpy, hãy tạo ra ma trận A10x7 với giá trị các phần tử của ma trận A
được sinh bởi:
- np.arrange()
- np.linspace()
- np.logspace()
- np.random.rand()

Sau mỗi lần ma trận được tạo ra, hãy xuất kết quả ra màn hình và cho biết:
- Số chiều và kích thước của ma trận A và ma trận AT

In [28]:
#Tạo ma trận bằng hàm arrange:
A = np.arange(0, 70, 1)
A.shape = (10,7)
A1 = np.transpose(A)
print(A)
print(A.ndim, A1.ndim)
print(A.shape,A1.shape)
#Tạo ma trận bằng hàm linspace:
B = np.linspace(0, 70, 70)
B.shape = (10,7)
B1 = np.transpose(B)
print(B)
print(B.ndim, B1.ndim)
print(B.shape,B1.shape)
#Tạo ma trận bằng hàm logspace:
C = np.logspace(0, 10, 70)
C.shape = (10,7)
C1 = np.transpose(C)
print(C)
print(C.ndim, C1.ndim)
print(C.shape,C1.shape)
#Tạo ma trận bằng hàm random.rand:
D = np.random.rand(1, 70)
D.shape =(10,7)
D1 = np.transpose(D)
print(D)
print(D.ndim, D1.ndim)
print(D.shape,D1.shape)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
2 2
(10, 7) (7, 10)
[[ 0.          1.01449275  2.02898551  3.04347826  4.05797101  5.07246377
   6.08695652]
 [ 7.10144928  8.11594203  9.13043478 10.14492754 11.15942029 12.17391304
  13.1884058 ]
 [14.20289855 15.2173913  16.23188406 17.24637681 18.26086957 19.27536232
  20.28985507]
 [21.30434783 22.31884058 23.33333333 24.34782609 25.36231884 26.37681159
  27.39130435]
 [28.4057971  29.42028986 30.43478261 31.44927536 32.46376812 33.47826087
  34.49275362]
 [35.50724638 36.52173913 37.53623188 38.55072464 39.56521739 40.57971014
  41.5942029 ]
 [42.60869565 43.62318841 44.63768116 45.65217391 46.66666667 47.68115942
  48.69565217]
 [49.71014493 50.72463768 51.73913043 52.75362319 53.76811594 54.7826087
  55.79710145]
 [56.8115942  57.82608696 58

Câu 3: Sử dụng thư viện Numpy, hãy:
- Chuyển ma trận A ở câu 2 thành vector. (Gợi ý: sử dụng hàm flatten())
- Chuyển vector vừa được tạo ra ở câu trên thành ma trận. (Gợi ý: sử dụng hàm reshape())

In [20]:
#Chuyển ma trận thành vector:
A1=A.flatten()
#Chuyển vector thành ma trận:
A = A1.reshape(10,7)
print(A1)
print(A)
#Chuyển ma trận thành vector:
B1=B.flatten()
#Chuyển vector thành ma trận:
B = B1.reshape(10,7)
print(B1)
print(B)
#Chuyển ma trận thành vector:
C1=C.flatten()
#Chuyển vector thành ma trận:
C = C1.reshape(10,7)
print(C1)
print(C)
#Chuyển ma trận thành vector:
D1=D.flatten()
#Chuyển vector thành ma trận:
D = D1.reshape(10,7)
print(D1)
print(D)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62]
 [63 64 65 66 67 68 69]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48. 49. 50. 51. 52. 53.
 54. 55. 56. 57. 58. 59. 60. 61. 62. 63. 64. 65. 66. 67. 68. 69.]
[[ 0.  1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12. 13.]
 [14. 15. 16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25. 26. 27.]
 [28. 29. 30. 31. 32. 33. 34.]
 [35. 36. 37. 38. 39. 40. 41.]
 [42. 43. 44. 45. 46. 47. 48.]
 [49. 50. 51. 52. 53. 54. 55.]
 [56. 57. 58

Câu 4: Sử dụng thư viện Numpy, hãy:
- Tạo ra 1 ma trận A10x15 với các giá trị được sinh ra bởi hàm logspace();
- Hãy trích rút dòng thứ 3 của ma trận A (tương ứng với 1 vector hàng);
- Hãy trích rút ra cột thứ 5 của ma trận A (tương ứng với 1 vector cột).

In [26]:
a = np.logspace(0, 150, num=150)
a.shape = (10,15)
a3 = a[3,:]
a5 = a[:,5]
print(a)
print("Trích dòng 3: ",a3)
print("Trích cột 5: ",a5)

[[1.e+000 1.e+001 1.e+002 1.e+003 1.e+004 1.e+005 1.e+006 1.e+007 1.e+008
  1.e+009 1.e+010 1.e+011 1.e+012 1.e+013 1.e+014]
 [1.e+015 1.e+016 1.e+017 1.e+018 1.e+019 1.e+020 1.e+021 1.e+022 1.e+023
  1.e+024 1.e+025 1.e+026 1.e+027 1.e+028 1.e+029]
 [1.e+030 1.e+031 1.e+032 1.e+033 1.e+034 1.e+035 1.e+036 1.e+037 1.e+038
  1.e+039 1.e+040 1.e+041 1.e+042 1.e+043 1.e+044]
 [1.e+045 1.e+046 1.e+047 1.e+048 1.e+049 1.e+050 1.e+051 1.e+052 1.e+053
  1.e+054 1.e+055 1.e+056 1.e+057 1.e+058 1.e+059]
 [1.e+060 1.e+061 1.e+062 1.e+063 1.e+064 1.e+065 1.e+066 1.e+067 1.e+068
  1.e+069 1.e+070 1.e+071 1.e+072 1.e+073 1.e+074]
 [1.e+075 1.e+076 1.e+077 1.e+078 1.e+079 1.e+080 1.e+081 1.e+082 1.e+083
  1.e+084 1.e+085 1.e+086 1.e+087 1.e+088 1.e+089]
 [1.e+090 1.e+091 1.e+092 1.e+093 1.e+094 1.e+095 1.e+096 1.e+097 1.e+098
  1.e+099 1.e+100 1.e+101 1.e+102 1.e+103 1.e+104]
 [1.e+105 1.e+106 1.e+107 1.e+108 1.e+109 1.e+110 1.e+111 1.e+112 1.e+113
  1.e+114 1.e+115 1.e+116 1.e+117 1.e+118 1.e+119]


Câu 5: Thực hiện các yêu cầu sau:
- Xây dựng hàm tính giá trị trung bình
- Xây dựng hàm tính giá trị trung vị
- Xây dựng hàm tính giá trị yếu vị
- Xây dựng hàm tính phương sai
- Xây dựng hàm tính độ lệch chuẩn
- Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()
- Áp dụng 5 hàm ở trên cho từng hàng của ma trận A
- Áp dụng 5 hàm ở trên cho từng cột của ma trận A
Gợi ý: tham khảo hàm apply_along_axis() đã học ở bài trước.

In [34]:
#Hàm tính giá trị trung bình:
def gtri_trbinh(A):
  S = 0
  for i in range(0,len(A)):
    S += A[i] 
  TB = S/len(A)
  return TB

#Hàm tính giá trị trung vị:
def gtri_trvi(A):
  if len(A) %2 != 0:
    Trvi = A[int((len(A)-1)/2)]
    return Trvi
  if len(A) %2 == 0:
    Trvi = (A[int(len(A)/2)] + A[int(len(A)/2 - 1)])/2
    return Trvi

#Hàm tính phương sai:
def tinhphsai(A):
  TB = gtri_trbinh(A)
  Tong = 0
  for i in range (0,len(A)):
    Tong += (A[i]- TB)**2
  phsai =  Tong/len(A)
  return phsai

#Hàm tính độ lệch chuẩn:
def dlchuan(A):
  phsai = tinhphsai(A)
  dlchuan = phsai**0.5
  return dlchuan


Hãy tạo ra ma trận A15x10 với các giá trị sinh bởi hàm arrange()

Áp dụng 5 hàm ở trên cho từng hàng của ma trận A

Áp dụng 5 hàm ở trên cho từng cột của ma trận A 
Gợi ý: tham khảo hàm apply_along_axis() đã học ở bài trước.

In [41]:
A = np.arange(0,150)
A = A.reshape((10,15))
print("Ma trận A: \n", A)

#Áp dụng kết quả cho từng hàng:
print("Trung bình: \n",np.apply_along_axis(gtri_trbinh,1,A))
print("Trung vị: \n", np.apply_along_axis(gtri_trvi,1,A))
print("Phương sai: \n", np.apply_along_axis(tinhphsai,1,A))
print("Độ lệch chuẩn: \n", np.apply_along_axis(dlchuan,1,A))

#Áp dụng kết quả cho từng cột:
print("Trung bình: \n",np.apply_along_axis(gtri_trbinh,0,A))
print("Trung vị: \n", np.apply_along_axis(gtri_trvi,0,A))
print("Phương sai: \n", np.apply_along_axis(tinhphsai,0,A))
print("Độ lệch chuẩn: \n", np.apply_along_axis(dlchuan,0,A))

Ma trận A: 
 [[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14]
 [ 15  16  17  18  19  20  21  22  23  24  25  26  27  28  29]
 [ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44]
 [ 45  46  47  48  49  50  51  52  53  54  55  56  57  58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74]
 [ 75  76  77  78  79  80  81  82  83  84  85  86  87  88  89]
 [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104]
 [105 106 107 108 109 110 111 112 113 114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134]
 [135 136 137 138 139 140 141 142 143 144 145 146 147 148 149]]
Trung bình: 
 [  7.  22.  37.  52.  67.  82.  97. 112. 127. 142.]
Trung vị: 
 [  7  22  37  52  67  82  97 112 127 142]
Phương sai: 
 [18.66666667 18.66666667 18.66666667 18.66666667 18.66666667 18.66666667
 18.66666667 18.66666667 18.66666667 18.66666667]
Độ lệch chuẩn: 
 [4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938 4.3204938
 4.3204938 